services:
  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
   # image: ghcr.io/kiquetal/saas-multitenant:20251107-amd64
    container_name: saas-multitenant-app
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/quarkus
      - QUARKUS_HTTP_ROOT_PATH=/borges
      - QUARKUS_LOG_LEVEL_APP=DEBUG
      - QUARKUS_LOG_APP_PATH=/deployments/logs/app-quarkus.log
      - QUARKUS_LOG_PATH=/deployments/logs/quarkus.log
    volumes:
      - app_logs:/deployments/logs
    networks:
      - saas-network
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        tag: docker.app
        fluentd-async: "true"
    depends_on:
      db:
        condition: service_healthy
      fluentd:
        condition: service_started

  db:
    image: postgres:18
    container_name: saas-multitenant-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quarkus
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - saas-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - saas-network
    volumes:
      - ./config/loki:/etc/loki
      - loki_data:/loki

  fluentd:
    build:
      context: ./config/fluentd
      dockerfile: Dockerfile
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./config/fluentd/conf:/fluentd/etc
      - app_logs:/fluentd/log
    networks:
      - saas-network
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_LOG_LEVEL=info
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - saas-network
    depends_on:
      - loki

volumes:
  postgres_data:
    name: saas-multitenant-data
  app_logs:
    name: saas-multitenant-logs
  loki_data:
    name: loki-data
  grafana_data:
    name: grafana-data

networks:
  saas-network:
    name: saas-network
    driver: bridge
